language: php
sudo: false

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_install:
  - composer self-update

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

script:
  - ./vendor/bin/phpunit --bootstrap src/Timer.php tests

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6668f52f3dd4e3f81960
    on_success: always
    on_failure: always
    on_start: false

